# Generated by Django 6.1.dev20251107214157 on 2025-11-09 09:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('subreddit', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_fetch_attempt', models.DateTimeField(blank=True, null=True)),
                ('post_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['last_updated'],
            },
        ),
        migrations.CreateModel(
            name='FetchQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_fetch_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_fetching', models.BooleanField(default=False)),
                ('current_country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moodapp.country')),
            ],
            options={
                'verbose_name': 'Fetch Queue',
                'verbose_name_plural': 'Fetch Queue',
            },
        ),
        migrations.CreateModel(
            name='RedditPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reddit_id', models.CharField(max_length=50, unique=True)),
                ('title', models.TextField()),
                ('score', models.IntegerField()),
                ('permalink', models.URLField(max_length=500)),
                ('author', models.CharField(max_length=100)),
                ('created_utc', models.DateTimeField()),
                ('num_comments', models.IntegerField()),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='moodapp.country')),
            ],
            options={
                'ordering': ['-created_utc'],
                'indexes': [models.Index(fields=['country', '-created_utc'], name='moodapp_red_country_243dad_idx'), models.Index(fields=['reddit_id'], name='moodapp_red_reddit__03ea35_idx')],
            },
        ),
    ]
