# Generated by Django 6.1.dev20251107214157 on 2025-11-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['last_updated'], 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='fetchqueue',
            options={'verbose_name_plural': 'Fetch Queue'},
        ),
        migrations.RemoveIndex(
            model_name='redditpost',
            name='moodapp_red_reddit__03ea35_idx',
        ),
        migrations.RemoveField(
            model_name='country',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='country',
            name='last_fetch_attempt',
        ),
        migrations.RemoveField(
            model_name='fetchqueue',
            name='current_country',
        ),
        migrations.AlterField(
            model_name='country',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='fetched_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='num_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='redditpost',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
