# Generated by Django 6.1.dev20251107214157 on 2025-11-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodapp', '0002_alter_country_options_alter_fetchqueue_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FetchStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_country', models.CharField(blank=True, max_length=100)),
                ('current_subreddit', models.CharField(blank=True, max_length=50)),
                ('is_fetching', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Fetch statuses',
            },
        ),
        migrations.AddField(
            model_name='country',
            name='emotion_score',
            field=models.IntegerField(default=5),
        ),
    ]
