# Generated by Django 6.1.dev20251107214157 on 2025-11-09 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodapp', '0003_fetchstatus_country_emotion_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_score', models.IntegerField()),
                ('ip_address', models.GenericIPAddressField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_moods', to='moodapp.country')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['country', '-submitted_at'], name='moodapp_use_country_592441_idx'), models.Index(fields=['ip_address', 'country', '-submitted_at'], name='moodapp_use_ip_addr_7d2367_idx')],
            },
        ),
    ]
