# Generated by Django 6.1.dev20251107214157 on 2025-11-09 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodapp', '0004_usermood'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_score', models.IntegerField()),
                ('comment_text', models.TextField(max_length=500)),
                ('ip_address', models.GenericIPAddressField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to='moodapp.country')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['-submitted_at'], name='moodapp_use_submitt_b9ccb3_idx')],
            },
        ),
    ]
